[files]
extend-exclude = [
    "contracts/lib",
    "**/*.yaml",
    "**/*.json",
    "**/fixtures/*.js",
    "**/*ffi*.js",
    "**/*mock*.rs",
    "**/*data*.rs",
    "cumulus/**",
    "smoketest/src/parachains",
    "smoketest/src/contracts",
    "polkadot-sdk",
]
