[files]
extend-exclude = [
    "contracts/lib",
    "**/*.yaml",
    "**/*.json",
    "**/fixtures/*.js",
    "**/*ffi*.js",
    "**/*mock*.rs",
    "**/*data*.rs",
    "polkadot-sdk/**",
    "smoketest/src/parachains",
    "smoketest/src/contracts",
    "lodestar/**",
    "go-ethereum/**",
    "go.work.sum",
    "parachain/Cargo.toml",
]
