#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod access_control;
pub mod address;
pub mod beefy_client;
pub mod beefy_client_mock;
pub mod bitfield;
pub mod bits;
pub mod bytes;
pub mod cheat_codes;
pub mod context;
pub mod counters;
pub mod ecdsa;
pub mod eip712;
pub mod enums;
pub mod erc165;
pub mod erc20;
pub mod erc20_permit;
pub mod i_access_control;
pub mod i_outbound_queue;
pub mod i_parachain_client;
pub mod i_recipient;
pub mod i_vault;
pub mod ierc165;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod ierc20_permit;
pub mod inbound_queue;
pub mod math;
pub mod memory;
pub mod merkle_proof;
pub mod mmr_proof;
pub mod mmr_proof_wrapper;
pub mod native_tokens;
pub mod native_tokens_types;
pub mod opaque_proof;
pub mod outbound_queue;
pub mod outbound_queue_mock;
pub mod ownable;
pub mod parachain_client;
pub mod parachain_client_mock;
pub mod recipient_mock;
pub mod safe_erc20;
pub mod scale_codec;
pub mod shared_types;
pub mod sovereign_treasury;
pub mod std_invariant;
pub mod strings;
pub mod substrate_types;
pub mod token_vault;
pub mod vault;
pub mod wrapped_token;
