[package]
name = "snowbridge-basic-channel-primitives"
version = "0.1.0"
edition = "2021"
authors = [ "Snowfork <contact@snowfork.com>" ]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { version = "3.0.0", package = "parity-scale-codec", features = [ "derive" ], default-features = false }

[features]
default = ["std"]
std = [
    "codec/std"
]
