[package]
name = "pallet-verifier-lightclient"
description = "Artemis Light Client Verifier Pallet"
version = "0.1.1"
edition = "2018"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/polkadot-ethereum"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { version = "1.3.6", package = "parity-scale-codec", default-features = false, features = ["derive"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
rlp = { version = "0.5", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }

artemis-core = { path = "../../primitives/core", default-features = false }
artemis-ethereum = { path = "../../primitives/ethereum", default-features = false }

ethash = { git = "https://github.com/Snowfork/ethash.git", branch = "master", default-features = false }

[dev-dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1" }
hex-literal = { version = "0.3.1" }
artemis-testutils = { path = "../../primitives/testutils" }
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "ethash/std",
    "frame-support/std",
    "frame-system/std",
    "rlp/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "artemis-core/std",
    "artemis-ethereum/std",
]
