//! Autogenerated weights for ethereum_beacon_client
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-27, STEPS: `10`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("/tmp/snowbridge/spec.json"), DB CACHE: 1024

// Executed Command:
// ./target/release/snowbridge
// benchmark
// pallet
// --chain
// /tmp/snowbridge/spec.json
// --execution=wasm
// --pallet
// ethereum_beacon_client
// --extrinsic
// *
// --steps
// 10
// --repeat
// 10
// --output
// pallets/ethereum-beacon-client/src/weights.rs
// --template
// templates/module-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for ethereum_beacon_client.
pub trait WeightInfo {
	fn sync_committee_period_update() -> Weight;
	fn import_finalized_header() -> Weight;
	fn import_execution_header() -> Weight;
	fn activate_bridge() -> Weight;
	fn deactivate_bridge() -> Weight;
	fn check_point_update() -> Weight;
	fn bls_fast_aggregate_verify_pre_aggregated() -> Weight;
	fn bls_fast_aggregate_verify() -> Weight;
	fn bls_fast_aggregate_verify_legacy() -> Weight;
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn sync_committee_period_update() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn import_finalized_header() -> Weight {
		Weight::from_parts(171_871_518_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn import_execution_header() -> Weight {
		Weight::from_parts(166_011_885_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn activate_bridge() -> Weight {
		Weight::from_parts(13_941_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn deactivate_bridge() -> Weight {
		Weight::from_parts(13_941_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn check_point_update() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn bls_fast_aggregate_verify_pre_aggregated() -> Weight {
		Weight::from_parts(28_368_043_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn bls_fast_aggregate_verify() -> Weight {
		Weight::from_parts(123_459_134_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn bls_fast_aggregate_verify_legacy() -> Weight {
		Weight::from_parts(123_459_134_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
