//! Autogenerated weights for ethereum_beacon_client
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-27, STEPS: `10`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("/tmp/snowbridge/spec.json"), DB CACHE: 1024

// Executed Command:
// ./target/release/snowbridge
// benchmark
// pallet
// --chain
// /tmp/snowbridge/spec.json
// --execution=wasm
// --pallet
// ethereum_beacon_client
// --extrinsic
// *
// --steps
// 10
// --repeat
// 10
// --output
// pallets/ethereum-beacon-client/src/weights.rs
// --template
// templates/module-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;
use crate::WeightInfo;
/// Weights for ethereum_beacon_client using the Snowbridge node and recommended hardware.
pub struct SnowbridgeWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SnowbridgeWeight<T> {
	fn sync_committee_period_update() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn import_finalized_header() -> Weight {
		Weight::from_parts(171_871_518_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn import_execution_header() -> Weight {
		Weight::from_parts(166_011_885_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// These weight are just by estimation and need benchmark later
	fn block_bridge() -> Weight {
		Weight::from_parts(1_000_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn begin_recovery() -> Weight {
		Weight::from_parts(10_000_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn sync_recovery() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn unblock_bridge() -> Weight {
		Weight::from_parts(1_000_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn init_sync() -> Weight {
		Weight::from_parts(200_000_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn sync_committee_period_update_without_verify_signed_header() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn verify_sync_committee_period_update_signatures() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn sync_committee_period_update_signatures_fast_aggregate_without_verify() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn sync_committee_period_update() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn import_finalized_header() -> Weight {
		Weight::from_parts(171_871_518_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn import_execution_header() -> Weight {
		Weight::from_parts(166_011_885_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn block_bridge() -> Weight {
		Weight::from_parts(1_000_000_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn begin_recovery() -> Weight {
		Weight::from_parts(10_000_000_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn sync_recovery() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn unblock_bridge() -> Weight {
		Weight::from_parts(1_000_000_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn init_sync() -> Weight {
		Weight::from_parts(200_000_000_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn sync_committee_period_update_without_verify_signed_header() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn verify_sync_committee_period_update_signatures() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn sync_committee_period_update_signatures_fast_aggregate_without_verify() -> Weight {
		Weight::from_parts(175_039_777_000 as u64, 0)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
}
