/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Precompiles_XcmInterface_sol_XCM__factory } from "./Precompiles_XcmInterface_sol_XCM__factory";
export { Precompiles_XcmUtil_sol_XcmUtils__factory } from "./Precompiles_XcmUtil_sol_XcmUtils__factory";
