// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2023 Snowfork <hello@snowfork.com>
pragma solidity 0.8.34;

// Used to verify merkle proofs generated by substrate's `binary-merkle-tree` (formerly
// paritytech/substrate, now archived into polkadot-sdk). Pinned to a specific commit so the
// referenced logic/line numbers stay stable; the `merkelize_row` name and comment text below are
// also greppable if the link ever moves:
//   https://github.com/paritytech/polkadot-sdk/blob/48a8a0689248e4fba3e6615e0c8c9c83f9df3343/substrate/utils/binary-merkle-tree/src/lib.rs#L359
// The crucial property reproduced below is the PROMOTION rule for odd layers: when a layer has an
// odd number of nodes the lone trailing node is carried up to the next layer UNCHANGED (not hashed
// with itself) — see `merkelize_row` upstream ("Odd number of items. Promote the item to the upper
// layer."). The matching proof generator used in production is the relayer's
// `relayer/crypto/merkle/merkle.go` (`Tree.Hash` / `Tree.MerklePath`, which `continue`s past the
// promoted node and emits no sibling for it). Keep all three in sync.
library SubstrateMerkleProof {
    /**
     * @notice Verify that a specific leaf element is part of the Merkle Tree at a specific position in the tree
     *
     * The tree would have been constructed using
     * https://paritytech.github.io/substrate/master/binary_merkle_tree/fn.merkle_root.html
     *
     * This implementation adapted from
     * https://paritytech.github.io/substrate/master/binary_merkle_tree/fn.verify_proof.html
     *
     * @param root the root of the merkle tree
     * @param leaf the leaf which needs to be proven
     * @param position the position of the leaf, index starting with 0
     * @param width the width or number of leaves in the tree
     * @param proof the array of proofs to help verify the leaf's membership, ordered from leaf to root
     * @return a boolean value representing the success or failure of the operation
     */
    function verify(
        bytes32 root,
        bytes32 leaf,
        uint256 position,
        uint256 width,
        bytes32[] calldata proof
    ) internal pure returns (bool) {
        (bool valid, bytes32 node) = computeRoot(leaf, position, width, proof);
        return valid && root == node;
    }

    /**
     * @notice Reconstruct the merkle root from a leaf and its proof.
     * @dev Walk the tree by geometry (not by proof.length) so that the number of sibling hashes
     *      is dictated by (position, width). A lone trailing node in an odd-width layer is
     *      promoted to the next layer unchanged and consumes no proof element, exactly as
     *      substrate's binary-merkle-tree builds the tree. `valid` is true only when `position`
     *      is in range and the proof length matches the canonical path for the leaf, which binds
     *      it to a single leaf position: a short (lone-promoted) proof can no longer alias onto
     *      the many other indices that share its leading decision bits. `root` is `bytes32(0)`
     *      whenever `valid` is false, so a caller that forgets to check `valid` fails closed.
     * @return valid whether the proof is structurally valid for `(position, width)`
     * @return root the reconstructed root, or `bytes32(0)` when `valid` is false
     */
    function computeRoot(bytes32 leaf, uint256 position, uint256 width, bytes32[] calldata proof)
        internal
        pure
        returns (bool, bytes32)
    {
        bytes32 node = leaf;
        if (position >= width) {
            return (false, bytes32(0));
        }
        uint256 i = 0;
        unchecked {
            while (width > 1) {
                // Promotion rule: the lone trailing node of an odd-width layer is carried up
                // unchanged and has no sibling, so it consumes no proof element. Mirrors
                // `merkelize_row` in substrate's binary-merkle-tree:
                // https://github.com/paritytech/polkadot-sdk/blob/48a8a0689248e4fba3e6615e0c8c9c83f9df3343/substrate/utils/binary-merkle-tree/src/lib.rs#L397
                bool promoted = position + 1 == width && width & 1 == 1;
                if (!promoted) {
                    // A genuine sibling is required here. A proof too short for this leaf's
                    // canonical path is invalid.
                    if (i >= proof.length) {
                        return (false, bytes32(0));
                    }
                    if (position & 1 == 1) {
                        node = efficientHash(proof[i], node);
                    } else {
                        node = efficientHash(node, proof[i]);
                    }
                    i++;
                }
                position = position >> 1;
                width = ((width - 1) >> 1) + 1;
            }
        }
        // The proof must contain exactly the canonical number of siblings -- no more, no less.
        if (i == proof.length) {
            return (true, node);
        }
        return (false, bytes32(0));
    }

    function efficientHash(bytes32 a, bytes32 b) internal pure returns (bytes32 value) {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x00, a)
            mstore(0x20, b)
            value := keccak256(0x00, 0x40)
        }
    }
}
