[settings]
node_spawn_timeout = 120
provider = "native"
timeout = 600

[relaychain]
default_command = "./polkadot"
default_args = [
    "--enable-offchain-indexing=true",
    "--pruning",
    "archive",
    "--disable-worker-version-check",
    "--state-cache-size=0",
]
chain = "polkadot-local"
chain_spec_path = "./polkadot-local.json"

[[relaychain.nodes]]
name = "alice"
args = ["--alice"]
validator = true

[[relaychain.nodes]]
name = "bob"
args = ["--bob"]
validator = true

[[relaychain.nodes]]
name = "charlie"
args = ["--charlie"]
validator = true

[[relaychain.nodes]]
name = "dave"
args = ["--dave"]
validator = true

## AssetHub
[[parachains]]
id = 1000
chain_spec_path = "./asset-hub-polkadot-local.json"
cumulus_based = true
chain = "asset-hub-polkadot-local"

[[parachains.collators]]
name = "assethub01"
command = "./polkadot-parachain"
args = ["--no-hardware-benchmarks"]

## Bridge Hub
[[parachains]]
id = 1002
chain_spec_path = "./bridge-hub-polkadot-local.json"
cumulus_based = true
chain = "bridge-hub-polkadot-local"

[[parachains.collators]]
args = [
    "--enable-offchain-indexing=true",
    "--pruning=archive",
    "--no-hardware-benchmarks",
]
name = "bridgehub01"
command = "./polkadot-parachain"
