[settings]
node_spawn_timeout = 120
provider = "native"
timeout = 600

[relaychain]
default_command = "{{BINDIR}}/polkadot"
default_args = [
    "--enable-offchain-indexing=true",
    "--pruning",
    "archive",
    "--disable-worker-version-check",
    "--state-cache-size=0",
]
chain_spec_command = "{{BINDIR}}/chain-spec-generator polkadot-local"

[[relaychain.nodes]]
name = "alice"
args = ["--alice"]
validator = true

[[relaychain.nodes]]
name = "bob"
args = ["--bob"]
validator = true

[[relaychain.nodes]]
name = "charlie"
args = ["--charlie"]
validator = true

[[relaychain.nodes]]
name = "dave"
args = ["--dave"]
validator = true

## AssetHub
[[parachains]]
id = 1000
chain_spec_command = "{{BINDIR}}/chain-spec-generator asset-hub-polkadot-local"
cumulus_based = true

[[parachains.collators]]
name = "assethub01"
command = "{{BINDIR}}/polkadot-parachain"
args = ["--no-hardware-benchmarks"]

[[parachains.collators]]
name = "assethub02"
command = "{{BINDIR}}/polkadot-parachain"
args = ["--no-hardware-benchmarks"]

## Bridge Hub
[[parachains]]
id = 1002
chain_spec_command = "{{BINDIR}}/chain-spec-generator bridge-hub-polkadot-local"
cumulus_based = true

[[parachains.collators]]
args = [
    "--enable-offchain-indexing=true",
    "--pruning=archive",
    "--force-authoring",
    "--no-hardware-benchmarks",
]
name = "bridgehub01"
command = "{{BINDIR}}/polkadot-parachain"

[[parachains.collators]]
args = [
    "--enable-offchain-indexing=true",
    "--pruning=archive",
    "--force-authoring",
    "--no-hardware-benchmarks",
]
name = "bridgehub02"
command = "{{BINDIR}}/polkadot-parachain"
