#!/usr/bin/env bash

set -e

# check typos
chronic typos .

# format contracts
(cd contracts && chronic forge fmt)

# lint and format for relayer codes
(cd relayer && chronic mage lint && chronic go fmt ./...)

# format rust
(cd parachain && chronic cargo +nightly-"$SNOWBRIDGE_RUST_NIGHTLY" fmt)
