package parachain

import (
	"context"
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	log "github.com/sirupsen/logrus"
	gsrpc "github.com/snowfork/go-substrate-rpc-client/v4"
	"github.com/snowfork/go-substrate-rpc-client/v4/types"
	"github.com/snowfork/snowbridge/relayer/chain/ethereum"
	"github.com/snowfork/snowbridge/relayer/chain/parachain"
	"github.com/snowfork/snowbridge/relayer/chain/relaychain"
	"github.com/snowfork/snowbridge/relayer/contracts"
)

type Scanner struct {
	config           *SourceConfig
	ethConn          *ethereum.Connection
	relayConn        *relaychain.Connection
	paraConn         *parachain.Connection
	paraID           uint32
	tasks            chan<- *Task
	eventQueryClient QueryClient
}

// Scans for all parachain message commitments for the configured parachain sourceID that need to be relayed and can be
// proven using the MMR root at the specified beefyBlockNumber of the relay chain.
//
// The algorithm works roughly like this:
//  1. Fetch channel nonce on both sides of the bridge and compare them
//  2. If the nonce on the parachain side is larger that means messages need to be relayed. If not then exit early.
//  3. Scan parachain blocks to figure out exactly which commitments need to be relayed.
//  4. For all the parachain blocks with unsettled commitments, determine the relay chain block number in which the
//     parachain block was included.
func (s *Scanner) Scan(ctx context.Context, beefyBlockNumber uint64) ([]*Task, error) {
	// fetch last parachain header that was finalized *before* the BEEFY block
	beefyBlockMinusOneHash, err := s.relayConn.API().RPC.Chain.GetBlockHash(uint64(beefyBlockNumber - 1))
	if err != nil {
		return nil, fmt.Errorf("fetch block hash for block %v: %w", beefyBlockNumber, err)
	}
	var paraHead types.Header
	ok, err := s.relayConn.FetchParachainHead(beefyBlockMinusOneHash, s.paraID, &paraHead)
	if err != nil {
		return nil, fmt.Errorf("fetch head for parachain %v at block %v: %w", s.paraID, beefyBlockMinusOneHash.Hex(), err)
	}
	if !ok {
		return nil, fmt.Errorf("parachain %v is not registered", s.paraID)
	}

	paraBlockNumber := uint64(paraHead.Number)
	paraBlockHash, err := s.paraConn.API().RPC.Chain.GetBlockHash(paraBlockNumber)
	if err != nil {
		return nil, fmt.Errorf("fetch parachain block hash for block %v: %w", paraBlockNumber, err)
	}

	tasks, err := s.findTasks(ctx, paraBlockNumber, paraBlockHash)
	if err != nil {
		return nil, err
	}

	return tasks, nil
}

// findTasks finds all the message commitments which need to be relayed
func (s *Scanner) findTasks(
	ctx context.Context,
	paraBlock uint64,
	paraHash types.Hash,
) ([]*Task, error) {
	// Fetch latest nonce in ethereum inbound queue
	inboundQueueAddress := common.HexToAddress(s.config.Contracts.InboundQueue)
	inboundQueueContract, err := contracts.NewInboundQueue(
		inboundQueueAddress,
		s.ethConn.Client(),
	)
	if err != nil {
		return nil, fmt.Errorf("create inbound queue contract for address '%v': %w", inboundQueueAddress, err)
	}

	options := bind.CallOpts{
		Pending: true,
		Context: ctx,
	}
	ethNonce, err := inboundQueueContract.Nonce(&options, s.config.LaneID)
	if err != nil {
		return nil, fmt.Errorf("fetch nonce from inbound queue contract for sourceID '%v': %w", s.config.LaneID, err)
	}
	log.WithFields(log.Fields{
		"nonce":    ethNonce,
		"sourceID": s.config.LaneID,
	}).Info("Checked latest nonce delivered to ethereum inbound queue")

	// Fetch latest nonce in parachain outbound queue
	sourceIDBytes := make([]byte, 4)
	binary.LittleEndian.PutUint32(sourceIDBytes, s.config.LaneID)
	paraNonceKey, err := types.CreateStorageKey(s.paraConn.Metadata(), "OutboundQueue", "Nonce", sourceIDBytes, nil)
	if err != nil {
		return nil, fmt.Errorf("create storage key for parachain outbound queue nonce with sourceID '%v': %w", s.config.LaneID, err)
	}
	var paraNonce types.U64
	ok, err := s.paraConn.API().RPC.State.GetStorage(paraNonceKey, &paraNonce, paraHash)
	if err != nil {
		return nil, fmt.Errorf("fetch nonce from parachain outbound queue with key '%v' and hash '%v': %w", paraNonceKey, paraHash, err)
	}
	if !ok {
		log.WithFields(log.Fields{
			"nonceKey":  paraNonceKey,
			"blockHash": paraHash,
		}).Info("Fetched empty nonce from parachain outbound queue")
		paraNonce = 0
	}
	log.WithFields(log.Fields{
		"nonce":    uint64(paraNonce),
		"sourceID": s.config.LaneID,
	}).Info("Checked latest nonce generated by parachain outbound queue")

	if !(uint64(paraNonce) > ethNonce) {
		return nil, nil
	}

	log.Info("Nonces are mismatched, scanning for commitments that need to be relayed")

	tasks, err := s.findTasksImpl(
		ctx,
		paraBlock,
		s.config.LaneID,
		ethNonce+1,
	)
	if err != nil {
		return nil, err
	}

	s.gatherProofInputs(tasks)

	return tasks, nil
}

// Searches for all lost commitments on the basic channel from the given parachain block number backwards
// until it finds the given nonces
func (s *Scanner) findTasksImpl(
	ctx context.Context,
	lastParaBlockNumber uint64,
	sourceID uint32,
	startingNonce uint64,
) ([]*Task, error) {
	log.WithFields(log.Fields{
		"sourceID":          sourceID,
		"nonce":             startingNonce,
		"latestBlockNumber": lastParaBlockNumber,
	}).Debug("Searching backwards from latest block on parachain to find block with nonce")

	scanOutboundQueueDone := false
	var tasks []*Task

	for currentBlockNumber := lastParaBlockNumber; currentBlockNumber > 0; currentBlockNumber-- {
		if scanOutboundQueueDone {
			break
		}

		log.WithFields(log.Fields{
			"blockNumber": currentBlockNumber,
		}).Debug("Checking header")

		blockHash, err := s.paraConn.API().RPC.Chain.GetBlockHash(currentBlockNumber)
		if err != nil {
			return nil, fmt.Errorf("fetch block hash for block %v: %w", currentBlockNumber, err)
		}

		header, err := s.paraConn.API().RPC.Chain.GetHeader(blockHash)
		if err != nil {
			return nil, fmt.Errorf("fetch header for block hash %v: %w", blockHash.Hex(), err)
		}

		digestItems, err := ExtractAuxiliaryDigestItems(header.Digest)
		if err != nil {
			return nil, err
		}
		if len(digestItems) == 0 {
			currentBlockNumber--
			continue
		}

		var digestItemCommitment *AuxiliaryDigestItemCommitment
		for _, digestItem := range digestItems {
			if digestItem.IsCommitment {
				digestItemCommitment = &digestItem.AsCommitment
				break
			}
		}
		if digestItemCommitment == nil {
			continue
		}

		event, err := s.eventQueryClient.QueryEvent(ctx, s.config.Parachain.Endpoint, blockHash)
		if err != nil {
			return nil, fmt.Errorf("query event: %w", err)
		}
		if event == nil {
			return nil, fmt.Errorf("event outboundQueue.Committed not found in block with commitment digest item")
		}

		if digestItemCommitment.Hash != event.Hash {
			return nil, fmt.Errorf("outbound queue commitment hash in digest item does not match the one in the Committed event")
		}

		// For the outbound channel, the commitment hash is the merkle root of the messages
		// https://github.com/Snowfork/snowbridge/blob/75a475cbf8fc8e13577ad6b773ac452b2bf82fbb/parachain/pallets/basic-channel/src/outbound/mod.rs#L275-L277
		// To verify it we fetch the message proof from the parachain
		result, err := scanForOutboundQueueProofs(
			s.paraConn.API(),
			digestItemCommitment.Hash,
			startingNonce,
			sourceID,
			event.Messages,
		)
		if err != nil {
			return nil, err
		}

		scanOutboundQueueDone = result.scanDone

		if len(result.proofs) > 0 {
			task := Task{
				Header:             header,
				BasicChannelProofs: &result.proofs,
				ProofInput:         nil,
				ProofOutput:        nil,
			}
			tasks = append(tasks, &task)
		}
	}

	// Reverse tasks, effectively sorting by ascending block number
	for i, j := 0, len(tasks)-1; i < j; i, j = i+1, j-1 {
		tasks[i], tasks[j] = tasks[j], tasks[i]
	}

	return tasks, nil
}

type PersistedValidationData struct {
	ParentHead             []byte
	RelayParentNumber      uint32
	RelayParentStorageRoot types.Hash
	MaxPOVSize             uint32
}

// For each task, gatherProofInputs will search to find the relay chain block
// in which that header was included as well as the parachain heads for that block.
func (s *Scanner) gatherProofInputs(
	tasks []*Task,
) error {
	for _, task := range tasks {

		log.WithFields(log.Fields{
			"ParaBlockNumber": task.Header.Number,
		}).Debug("Gathering proof inputs for parachain header")

		relayBlockNumber, err := s.findInclusionBlockNumber(uint64(task.Header.Number))
		if err != nil {
			return fmt.Errorf("find inclusion block number for parachain block %v: %w", task.Header.Number, err)
		}

		relayBlockHash, err := s.relayConn.API().RPC.Chain.GetBlockHash(relayBlockNumber)
		if err != nil {
			return fmt.Errorf("fetch relaychain block hash: %w", err)
		}

		parachainHeads, err := s.relayConn.FetchParachainHeads(relayBlockHash)
		if err != nil {
			return fmt.Errorf("fetch parachain heads: %w", err)
		}

		task.ProofInput = &ProofInput{
			ParaID:           s.paraID,
			RelayBlockNumber: relayBlockNumber,
			ParaHeads:        parachainHeads,
		}
	}

	return nil
}

// The process for finalizing a backed parachain header times out after these many blocks:
const FinalizationTimeout = 4

// Find the relaychain block in which a parachain header was included (finalized). This usually happens
// 2-3 blocks after the relaychain block in which the parachain header was backed.
func (s *Scanner) findInclusionBlockNumber(
	paraBlockNumber uint64,
) (uint64, error) {
	validationDataKey, err := types.CreateStorageKey(s.paraConn.Metadata(), "ParachainSystem", "ValidationData", nil, nil)
	if err != nil {
		return 0, fmt.Errorf("create storage key: %w", err)
	}

	paraBlockHash, err := s.paraConn.API().RPC.Chain.GetBlockHash(paraBlockNumber)
	if err != nil {
		return 0, fmt.Errorf("fetch parachain block hash: %w", err)
	}

	var validationData PersistedValidationData
	ok, err := s.paraConn.API().RPC.State.GetStorage(validationDataKey, &validationData, paraBlockHash)
	if err != nil {
		return 0, fmt.Errorf("fetch PersistedValidationData for block %v: %w", paraBlockHash.Hex(), err)
	}
	if !ok {
		return 0, fmt.Errorf("PersistedValidationData not found for block %v", paraBlockHash.Hex())
	}

	startBlock := validationData.RelayParentNumber + 1
	for i := validationData.RelayParentNumber + 1; i < startBlock+FinalizationTimeout; i++ {
		relayBlockHash, err := s.relayConn.API().RPC.Chain.GetBlockHash(uint64(i))
		if err != nil {
			return 0, fmt.Errorf("fetch relaychain block hash: %w", err)
		}

		var paraHead types.Header
		ok, err := s.relayConn.FetchParachainHead(relayBlockHash, s.paraID, &paraHead)
		if err != nil {
			return 0, fmt.Errorf("fetch head for parachain %v at block %v: %w", s.paraID, relayBlockHash.Hex(), err)
		}
		if !ok {
			return 0, fmt.Errorf("parachain %v is not registered", s.paraID)
		}

		if paraBlockNumber == uint64(paraHead.Number) {
			return uint64(i), nil
		}
	}

	return 0, fmt.Errorf("scan terminated")
}

func scanForOutboundQueueProofs(
	api *gsrpc.SubstrateAPI,
	digestItemHash types.H256,
	startingNonce uint64,
	sourceID uint32,
	messages []OutboundQueueMessage,
) (*struct {
	proofs   []MessageProof
	scanDone bool
}, error) {
	var scanDone bool
	proofs := []MessageProof{}

	for messageIndex, message := range messages {
		if message.Origin != sourceID {
			continue
		}

		messageNonceBigInt := big.Int(message.Nonce)
		messageNonce := messageNonceBigInt.Uint64()

		// TODO: Won't this also happen if a block's messages have been partially relayed?
		// This case will be hit when there are no new messages to relay.
		if messageNonce < startingNonce {
			log.Debugf(
				"Halting scan for sourceID '%v'. Messages not committed yet on outbound channel",
				message.Origin,
			)
			scanDone = true
			break
		}

		messageProof, err := fetchMessageProof(api, digestItemHash, messageIndex, message)
		if err != nil {
			return nil, err
		}
		// check merkle root calculated from message proof is same as the digest hash from header
		if messageProof.Proof.Root != digestItemHash {
			log.Warnf(
				"Halting scan for sourceID '%v'. Outbound queue proof root doesn't match digest item's commitment hash",
				message.Origin,
			)
			scanDone = true
			break
		}

		// Collect these commitments
		proofs = append(proofs, messageProof)

		if messageNonce == startingNonce {
			// Terminate scan
			scanDone = true
		}
	}

	return &struct {
		proofs   []MessageProof
		scanDone bool
	}{
		proofs:   proofs,
		scanDone: scanDone,
	}, nil
}

func fetchMessageProof(
	api *gsrpc.SubstrateAPI,
	commitmentHash types.H256,
	messageIndex int,
	message OutboundQueueMessage,
) (MessageProof, error) {
	var proofHex string
	var rawProof RawMerkleProof
	var messageProof MessageProof

	commitmentHashHex, err := types.EncodeToHexString(commitmentHash)
	if err != nil {
		return messageProof, fmt.Errorf("encode commitmentHash(%v): %w", commitmentHash, err)
	}

	err = api.Client.Call(&proofHex, "basicOutboundQueue_getMerkleProof", commitmentHashHex, messageIndex)
	if err != nil {
		return messageProof, fmt.Errorf("call rpc basicOutboundQueue_getMerkleProof(%v, %v): %w", commitmentHash, messageIndex, err)
	}

	err = types.DecodeFromHexString(proofHex, &rawProof)
	if err != nil {
		return messageProof, fmt.Errorf("decode merkle proof: %w", err)
	}

	proof, err := NewMerkleProof(rawProof)
	if err != nil {
		return messageProof, fmt.Errorf("decode merkle proof: %w", err)
	}

	return MessageProof{Message: message, Proof: proof}, nil
}
