const registry = {
    environment: {
        name: "local_e2e",
        ethChainId: 11155111,
        beaconApiUrl: "http://127.0.0.1:9596",
        ethereumChains: {
            "11155111": "ws://127.0.0.1:8546",
        },
        relaychainUrl: "ws://127.0.0.1:9944",
        parachains: {
            "1000": "ws://127.0.0.1:12144",
            "1002": "ws://127.0.0.1:11144",
            "2000": "ws://127.0.0.1:13144",
        },
        gatewayContract: "0xb1185ede04202fe62d38f5db72f71e38ff3e8305",
        beefyContract: "0x83428c7db9815f482a39a1715684dcf755021997",
        assetHubParaId: 1000,
        bridgeHubParaId: 1002,
        v2_parachains: [1000],
        indexerGraphQlUrl: "http://127.0.0.1/does/not/exist",
    },
    routes: [],
    registry: {
        timestamp: "2026-03-03T03:46:58.680Z",
        environment: "local_e2e",
        ethChainId: 11155111,
        gatewayAddress: "0xb1185ede04202fe62d38f5db72f71e38ff3e8305",
        assetHubParaId: 1000,
        bridgeHubParaId: 1002,
        relaychain: {
            tokenSymbols: "undefined",
            tokenDecimals: NaN,
            ss58Format: 42,
            isEthereum: false,
            accountType: "AccountId32",
            name: "Westend Local Testnet",
            specName: "westend",
            specVersion: 1021002,
        },
        bridgeHub: {
            tokenSymbols: "WND",
            tokenDecimals: 12,
            ss58Format: 42,
            isEthereum: false,
            accountType: "AccountId32",
            name: "Westend BridgeHub Local",
            specName: "bridge-hub-westend",
            specVersion: 1021002,
        },
        ethereumChains: {
            ethereum_11155111: {
                kind: "ethereum",
                id: 11155111,
                name: "sepolia",
                assets: {},
                key: "ethereum_11155111",
                baseDeliveryGas: 120000n,
            },
        },
        parachains: {
            polkadot_1000: {
                id: 1000,
                kind: "polkadot",
                key: "polkadot_1000",
                features: {
                    hasPalletXcm: true,
                    hasDryRunApi: true,
                    hasTxPaymentApi: true,
                    hasDryRunRpc: true,
                    hasDotBalance: true,
                    hasEthBalance: false,
                    hasXcmPaymentApi: true,
                    supportsAliasOrigin: true,
                    xcmVersion: "v5",
                    supportsV2: true,
                },
                info: {
                    tokenSymbols: "WND",
                    tokenDecimals: 12,
                    ss58Format: 42,
                    isEthereum: false,
                    accountType: "AccountId32",
                    name: "Westend Asset Hub Local",
                    specName: "westmint",
                    specVersion: 1021004,
                },
                assets: {},
                estimatedExecutionFeeDOT: 0n,
                estimatedDeliveryFeeDOT: 0n,
            },
            polkadot_2000: {
                id: 2000,
                kind: "polkadot",
                key: "polkadot_2000",
                features: {
                    hasPalletXcm: true,
                    hasDryRunApi: true,
                    hasTxPaymentApi: true,
                    hasDryRunRpc: true,
                    hasDotBalance: true,
                    hasEthBalance: false,
                    hasXcmPaymentApi: true,
                    supportsAliasOrigin: true,
                    xcmVersion: "v5",
                    supportsV2: false,
                },
                info: {
                    tokenSymbols: "undefined",
                    tokenDecimals: NaN,
                    ss58Format: 42,
                    isEthereum: false,
                    accountType: "AccountId32",
                    name: "Penpal Parachain",
                    specName: "penpal-parachain",
                    specVersion: 1,
                },
                assets: {},
                estimatedExecutionFeeDOT: 3276800000n,
                estimatedDeliveryFeeDOT: 31450000000n,
            },
        },
    },
} as const
export default registry
