// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.34;

import {BeefyClient} from "../../src/BeefyClient.sol";

/**
 * @dev Test helper: pack a legacy `ValidatorProof[]` (the shape the JSON fixtures are encoded
 * in, and the shape the relayer used to send) into the `CompactValidatorProofs` that
 * `submitFinal` / `submitFiatShamir` now take.
 *
 * `proofs` must already be ordered by ascending validator index -- which the fixtures are,
 * because they are generated by walking the set bits of the sample bitfield.
 */
library CompactProofLib {
    function toCompact(BeefyClient.ValidatorProof[] memory proofs)
        internal
        pure
        returns (BeefyClient.CompactValidatorProofs memory compact)
    {
        bytes memory sigs;
        uint256 total;
        for (uint256 i = 0; i < proofs.length; i++) {
            sigs = bytes.concat(sigs, proofs[i].r, proofs[i].s, bytes1(proofs[i].v));
            total += proofs[i].proof.length;
        }

        bytes32[] memory siblings = new bytes32[](total);
        uint256 k;
        for (uint256 i = 0; i < proofs.length; i++) {
            for (uint256 j = 0; j < proofs[i].proof.length; j++) {
                siblings[k++] = proofs[i].proof[j];
            }
        }

        compact = BeefyClient.CompactValidatorProofs({signatures: sigs, siblings: siblings});
    }

    /**
     * @dev Give slot `a` the signature that belongs to slot `b`, leaving every Merkle path in
     * place. This is the compact-format equivalent of the old "tamper with `account`/`index`"
     * negative tests: a validator the sample did not select tries to answer a sampled slot.
     * The recovered signer no longer matches the leaf the path proves, so it must be rejected.
     */
    function withSubstitutedSigner(BeefyClient.ValidatorProof[] memory proofs, uint256 a, uint256 b)
        internal
        pure
        returns (BeefyClient.CompactValidatorProofs memory)
    {
        (uint8 v, bytes32 r, bytes32 s) = (proofs[a].v, proofs[a].r, proofs[a].s);
        (proofs[a].v, proofs[a].r, proofs[a].s) = (proofs[b].v, proofs[b].r, proofs[b].s);
        (proofs[b].v, proofs[b].r, proofs[b].s) = (v, r, s);
        return toCompact(proofs);
    }

    /// @dev Same, for a single proof -- convenient for negative tests.
    function toCompact(BeefyClient.ValidatorProof memory proof)
        internal
        pure
        returns (BeefyClient.CompactValidatorProofs memory)
    {
        BeefyClient.ValidatorProof[] memory one = new BeefyClient.ValidatorProof[](1);
        one[0] = proof;
        return toCompact(one);
    }
}
