// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.34;

import {BeefyClient} from "../../src/BeefyClient.sol";

/**
 * @dev Test helper: pack a legacy `ValidatorProof[]` (the shape the JSON fixtures are encoded
 * in, and the shape the relayer used to send) into the `CompactValidatorProofs` that
 * `submitFinal` / `submitFiatShamir` now take.
 *
 * `proofs` must already be ordered by ascending validator index -- which the fixtures are,
 * because they are generated by walking the set bits of the sample bitfield.
 */
library CompactProofLib {
    function toCompact(BeefyClient.ValidatorProof[] memory proofs, uint256 width)
        internal
        pure
        returns (BeefyClient.CompactValidatorProofs memory compact)
    {
        bytes memory sigs;
        for (uint256 i = 0; i < proofs.length; i++) {
            sigs = bytes.concat(sigs, proofs[i].r, proofs[i].s, bytes1(proofs[i].v));
        }
        compact = BeefyClient.CompactValidatorProofs({
            signatures: sigs, siblings: multiproof(proofs, width)
        });
    }

    /**
     * @dev Build the multiproof siblings from the per-validator paths by running the same fold
     * as `SubstrateMerkleProof.computeMultiRoot`. Every node in the fold tracks one leaf whose
     * path runs through it, and how far along that path it is; where the fold needs a sibling,
     * it is that path's next element. A path that runs out (as the aliasing tests' paths do)
     * yields zero, so the contract rejects on the root rather than the test panicking.
     */
    function multiproof(BeefyClient.ValidatorProof[] memory proofs, uint256 width)
        internal
        pure
        returns (bytes32[] memory siblings)
    {
        uint256 n = proofs.length;
        uint256[] memory positions = new uint256[](n);
        uint256[] memory origin = new uint256[](n);
        uint256[] memory cursor = new uint256[](n);
        for (uint256 i = 0; i < n; i++) {
            positions[i] = proofs[i].index;
            origin[i] = i;
        }
        uint256 depth;
        for (uint256 w = width; w > 1; w = ((w - 1) >> 1) + 1) {
            depth++;
        }
        siblings = new bytes32[](n * depth);
        uint256 next;

        while (width > 1) {
            uint256 m;
            for (uint256 i = 0; i < n; i++) {
                uint256 p = positions[i];
                uint256 o = origin[i];
                uint256 c = cursor[i];
                if (p + 1 == width && width & 1 == 1) {
                    // promoted: no sibling on this layer
                } else if (p & 1 == 0 && i + 1 < n && positions[i + 1] == p + 1) {
                    c++;
                    i++;
                } else {
                    bytes32[] memory path = proofs[o].proof;
                    siblings[next++] = c < path.length ? path[c] : bytes32(0);
                    c++;
                }
                positions[m] = p >> 1;
                origin[m] = o;
                cursor[m] = c;
                m++;
            }
            n = m;
            width = ((width - 1) >> 1) + 1;
        }

        assembly {
            mstore(siblings, next)
        }
    }

    /**
     * @dev Give slot `a` the signature that belongs to slot `b`, leaving every Merkle path in
     * place. This is the compact-format equivalent of the old "tamper with `account`/`index`"
     * negative tests: a validator the sample did not select tries to answer a sampled slot.
     * The recovered signer no longer matches the leaf the path proves, so it must be rejected.
     */
    function withSubstitutedSigner(
        BeefyClient.ValidatorProof[] memory proofs,
        uint256 width,
        uint256 a,
        uint256 b
    ) internal pure returns (BeefyClient.CompactValidatorProofs memory) {
        (uint8 v, bytes32 r, bytes32 s) = (proofs[a].v, proofs[a].r, proofs[a].s);
        (proofs[a].v, proofs[a].r, proofs[a].s) = (proofs[b].v, proofs[b].r, proofs[b].s);
        (proofs[b].v, proofs[b].r, proofs[b].s) = (v, r, s);
        return toCompact(proofs, width);
    }

    /// @dev Same, for a single proof -- convenient for negative tests.
    function toCompact(BeefyClient.ValidatorProof memory proof, uint256 width)
        internal
        pure
        returns (BeefyClient.CompactValidatorProofs memory)
    {
        BeefyClient.ValidatorProof[] memory one = new BeefyClient.ValidatorProof[](1);
        one[0] = proof;
        return toCompact(one, width);
    }
}
