#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo 'Running pre-commit hook...'

# check typos
chronic typos .

# lint and format for core contracts and typescript codes
(cd core && chronic pnpm lint && pnpm format)

# lint and format for relayer codes
(cd relayer && chronic mage lint && chronic go fmt ./...)

# comment here and run `cargo +nightly fmt` manually without nix for https://github.com/oxalica/rust-overlay/issues/66#issuecomment-993816000
#(cd parachain && SKIP_WASM_BUILD= cargo +nightly fmt --all)

check_duplicate_versions() {
        local duplicates=`grep -Ei "source = \"git.*$1" cumulus/Cargo.lock parachain/Cargo.lock | sed 's/\.git//g' | sort -u`
	echo $duplicates
        local version_count=`echo $duplicates | awk -F':' '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | sort -u | wc -l | xargs`
	echo $version_count
        if [ "$version_count" != "1" ]; then
                echo Duplicate $1 versions detected
                echo $duplicates
                exit 1
        fi
}

check_duplicate_versions substrate
#check_duplicate_versions polkadot

echo 'Pre-commit hook successful!'
