#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint and format for core contracts and typescript codes
cd core && pnpm lint && pnpm format && cd ..

# lint and format for relayer codes
cd relayer && mage lint && go fmt ./...

