#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo 'Running pre-commit hook...'

# check typos
chronic typos .

# lint and format for core contracts and typescript codes
cd core && chronic pnpm lint && chronic pnpm format && cd ..

# lint and format for relayer codes
cd relayer && chronic mage lint && chronic go fmt ./...

echo 'Pre-commit hook successful!'
