name: api

on:
  push:
    paths:
      - "contracts/src/**/*.sol"
      - "web/**"
      - "!web/packages/test*"
    branches:
      - main
  pull_request:
    paths:
      - "contracts/src/**/*.sol"
      - "web/**"
      - "!web/packages/test*"

jobs:
  build-contracts:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test
        working-directory: contracts
        run: forge test
        run: ls ../../../contracts

  build-api:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    needs: build-contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build Contract Types
        working-directory: web/packages/contract-types
        run: |
          pnpm install
          ls ../../../contracts
          pnpm typechain
          pnpm build

      - name: Build API
        working-directory: web/packages/api
        run: |
          pnpm install
          pnpm build

      - name: Build UI
        working-directory: web/packages/ui
        run: |
          pnpm install
          pnpm run build

      - name: Publish Contract Types
        working-directory: web/packages/contract-types
        run: |
          pnpm publish

      - name: Publish API
        working-directory: web/packages/api
        run: |
          pnpm publish
      
