name: coverage

on:
  push:
    paths:
      - "contracts/**"
      - "!contracts/**/README.md"
    branches:
      - main
  pull_request:

jobs:
  contracts:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Test
        working-directory: contracts
        run: forge test
      - name: Coverage
        working-directory: contracts
        run: forge coverage --report=lcov --via-ir
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          working-directory: contracts
          files: lcov.info
          flags: solidity

  rust:
    runs-on: snowbridge-runner
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
      RUSTFLAGS: -C debuginfo=1
      SKIP_WASM_BUILD: 1
      RUST_MIN_STACK: 8388608
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/snowfork/polkadot-sdk'
          ref: ${{ github.head_ref }}
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup rust toolchain
        run: rustup show
      - name: run coverage test
        working-directory: polkadot-sdk
        run: >
          cargo install cargo-tarpaulin@0.27.0 &&
          cargo tarpaulin
          --workspace
          --engine llvm
          --out xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          working-directory: polkadot-sdk
          files: cobertura.xml
          flags: rust
