name: label PRs

on:
  pull_request:

jobs:
  labeler:
    if: false
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
         sync-labels: true
