name: relayer

on:
  push:
    branches:
      - solochain
  pull_request:

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'
          cache-dependency-path: relayer/go.sum
      - name: Install Go tools
        run: |
          go install github.com/magefile/mage@v1.15.0
          go install github.com/ferranbt/fastssz/sszgen@v0.1.3
          go install github.com/ethereum/go-ethereum/cmd/abigen@v1.14.8

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Install dependencies
        working-directory: relayer
        run: go mod download

      - name: Add gopath to bin
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build relayer binary
        working-directory: relayer
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 mage build

      - name: Test
        working-directory: relayer
        run: go test -v ./...

      - name: Upload relayer binary
        uses: actions/upload-artifact@v4
        with:
          name: snowbridge-relay
          path: relayer/build/snowbridge-relay

  docker-build-and-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Download relayer binary
        uses: actions/download-artifact@v4
        with:
          name: snowbridge-relay
          path: relayer/build

      - name: Make relayer binary executable
        run: chmod +x relayer/build/snowbridge-relay

      - name: Run build-local-docker.sh
        working-directory: relayer
        run: ./build-local-docker.sh

      - name: Test Docker image with --help
        run: docker run --rm snowbridge-relay:local --help

  docker-publish:
    needs: docker-build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download relayer binary
        uses: actions/download-artifact@v4
        with:
          name: snowbridge-relay
          path: relayer/build

      - name: Make relayer binary executable
        run: chmod +x relayer/build/snowbridge-relay
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine Docker tag value
        id: docker_tag_value
        shell: bash
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            TAG_VALUE="latest"
          else
            TAG_VALUE="$GITHUB_HEAD_REF"
          fi
          SANITIZED_TAG_VALUE=$(echo "$TAG_VALUE" \
            | tr '/' '-' \
            | sed 's/[^A-Za-z0-9._-]/-/g')
          echo "value=$SANITIZED_TAG_VALUE" >> $GITHUB_OUTPUT
          
      

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          push: true
          tags: moonsonglabs/snowbridge-relayer:${{ steps.docker_tag_value.outputs.value }}