name: release

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-2022-01-20
          target: wasm32-unknown-unknown
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path parachain/Cargo.toml --release
      - uses: actions/upload-artifact@v1
        with:
          name: artemis-node
          path: parachain/target/release/artemis-node
